# Generated by Django 6.0.1 on 2026-03-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
