# Generated by Django 6.0.4 on 2026-07-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_forum_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрен'),
        ),
    ]
